----------------------------------------------------------------------
-- ZugZug Keys — WCL-derived lust calls (AUTO-GENERATED)
-- Where the top M+ groups actually cast Bloodlust/Heroism/Time Warp,
-- derived weekly from WarcraftLogs top runs and regenerated by
-- scripts/update-lustdata.ts. Do not edit by hand — hand-curated
-- overrides belong in LustData.lua instead.
--
-- Generated: 2026-07-03T00:05:22.294Z
--
-- Call shapes (matched in-game by fuzzy boss-name comparison):
--   { type = "boss", bossName = X }             lust on that boss engage
--   { type = "afterBoss", pullOffset = N }      Nth pack from the run start
--   { type = "afterBoss", anchorBossName = X, pullOffset = N }
--                                               Nth pack after boss X dies
----------------------------------------------------------------------

ZugZugKeysWclLustData = {
  ["Algeth'ar Academy"] = {
    runsAnalyzed = 4,
    keystoneLevels = "23/23/23/23",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 4, runsAnalyzed = 4 },
      { type = "boss", bossName = "Crawth", support = 4, runsAnalyzed = 4 },
      { type = "afterBoss", anchorBossName = "Vexamus", pullOffset = 2, support = 4, runsAnalyzed = 4 },
    },
  },
  ["Magisters' Terrace"] = {
    runsAnalyzed = 5,
    keystoneLevels = "25/24/24/24/24",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "afterBoss", anchorBossName = "Arcanotron Custos", pullOffset = 1, support = 4, runsAnalyzed = 5 },
      { type = "boss", bossName = "Gemellus", support = 4, runsAnalyzed = 5 },
    },
  },
  ["Maisara Caverns"] = {
    runsAnalyzed = 5,
    keystoneLevels = "25/24/24/24/24",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "afterBoss", anchorBossName = "Muro'jin and Nekraxx", pullOffset = 1, support = 4, runsAnalyzed = 5 },
      { type = "boss", bossName = "Vordaza", support = 5, runsAnalyzed = 5 },
    },
  },
  ["Nexus-Point Xenas"] = {
    runsAnalyzed = 5,
    keystoneLevels = "24/24/24/24/24",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "boss", bossName = "Corewarden Nysarra", support = 5, runsAnalyzed = 5 },
      { type = "boss", bossName = "Lothraxion", support = 5, runsAnalyzed = 5 },
    },
  },
  ["Pit of Saron"] = {
    runsAnalyzed = 5,
    keystoneLevels = "24/24/24/24/24",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "boss", bossName = "Forgemaster Garfrost", support = 5, runsAnalyzed = 5 },
      { type = "afterBoss", anchorBossName = "Ick and Krick", pullOffset = 1, support = 5, runsAnalyzed = 5 },
    },
  },
  ["Seat of Triumvirate"] = {
    runsAnalyzed = 5,
    keystoneLevels = "24/24/23/23/23",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "afterBoss", anchorBossName = "Zuraal the Ascended", pullOffset = 3, support = 4, runsAnalyzed = 5 },
      { type = "boss", bossName = "Viceroy Nezhar", support = 5, runsAnalyzed = 5 },
    },
  },
  ["Skyreach"] = {
    runsAnalyzed = 5,
    keystoneLevels = "23/23/23/23/23",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "boss", bossName = "Araknath", support = 5, runsAnalyzed = 5 },
      { type = "boss", bossName = "High Sage Viryx", support = 5, runsAnalyzed = 5 },
    },
  },
  ["Windrunner Spire"] = {
    runsAnalyzed = 5,
    keystoneLevels = "24/24/24/24/24",
    generatedAt = "2026-07-03T00:05:22.294Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5 },
      { type = "afterBoss", anchorBossName = "Emberdawn", pullOffset = 2, support = 5, runsAnalyzed = 5 },
      { type = "boss", bossName = "Restless Heart", support = 5, runsAnalyzed = 5 },
    },
  },
}
