----------------------------------------------------------------------
-- ZugZug Keys — WCL-derived lust calls (AUTO-GENERATED)
-- Where the top M+ groups actually cast Bloodlust/Heroism/Time Warp,
-- derived weekly from WarcraftLogs top runs and regenerated by
-- scripts/update-lustdata.ts. Do not edit by hand — hand-curated
-- overrides belong in LustData.lua instead.
--
-- Generated: 2026-09-10T11:23:35.039Z
--
-- Call shapes (matched in-game by fuzzy boss-name comparison):
--   { type = "boss", bossName = X }             lust on that boss engage
--   { type = "afterBoss", pullOffset = N }      Nth pack from the run start
--   { type = "afterBoss", anchorBossName = X, pullOffset = N }
--                                               Nth pack after boss X dies
----------------------------------------------------------------------

ZugZugKeysWclLustData = {
  ["Altar of Fangs"] = {
    runsAnalyzed = 5,
    keystoneLevels = "20/20/20/20/20",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 4, runsAnalyzed = 5, atMs = 24465 },
      { type = "afterBoss", anchorBossName = "Rav'i", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 700381 },
      { type = "afterBoss", anchorBossName = "The Writhing Coil", pullOffset = 3, support = 4, runsAnalyzed = 5, atMs = 1420814 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "18",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 100, runsAnalyzed = 100, atMs = 23947 },
          { type = "afterBoss", anchorBossName = "Rav'i", pullOffset = 1, support = 96, runsAnalyzed = 100, atMs = 652393 },
          { type = "afterBoss", anchorBossName = "The Writhing Coil", pullOffset = 3, support = 62, runsAnalyzed = 100, atMs = 1343420 },
        },
      },
      p01 = {
        runsAnalyzed = 100,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 97, runsAnalyzed = 100, atMs = 23773 },
          { type = "afterBoss", anchorBossName = "Rav'i", pullOffset = 1, support = 97, runsAnalyzed = 100, atMs = 686587 },
          { type = "afterBoss", anchorBossName = "The Writhing Coil", pullOffset = 3, support = 62, runsAnalyzed = 100, atMs = 1399382 },
        },
      },
    },
  },
  ["Den of Nalorakk"] = {
    runsAnalyzed = 5,
    keystoneLevels = "21/21/21/21/21",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 46816 },
      { type = "afterBoss", anchorBossName = "Sentinel of Winter", pullOffset = 3, support = 5, runsAnalyzed = 5, atMs = 1489049 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 99,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 96, runsAnalyzed = 99, atMs = 47168 },
          { type = "boss", bossName = "Nalorakk", support = 83, runsAnalyzed = 99, atMs = 1518095 },
        },
      },
      p01 = {
        runsAnalyzed = 100,
        keystoneLevels = "20",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 97, runsAnalyzed = 100, atMs = 47841 },
          { type = "boss", bossName = "Nalorakk", support = 59, runsAnalyzed = 100, atMs = 1616864 },
        },
      },
    },
  },
  ["King's Rest"] = {
    runsAnalyzed = 5,
    keystoneLevels = "21/21/21/20/20",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 3, runsAnalyzed = 5, atMs = 51937 },
      { type = "boss", bossName = "King Dazar", support = 5, runsAnalyzed = 5, atMs = 1799888 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 79, runsAnalyzed = 100, atMs = 51632 },
          { type = "boss", bossName = "King Dazar", support = 91, runsAnalyzed = 100, atMs = 1657768 },
        },
      },
      p01 = {
        runsAnalyzed = 100,
        keystoneLevels = "20",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 82, runsAnalyzed = 100, atMs = 50344 },
          { type = "boss", bossName = "King Dazar", support = 90, runsAnalyzed = 100, atMs = 1770680 },
        },
      },
    },
  },
  ["Murder Row"] = {
    runsAnalyzed = 5,
    keystoneLevels = "21/21/21/21/21",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 18363 },
      { type = "boss", bossName = "Zaen Bladesorrow", support = 5, runsAnalyzed = 5, atMs = 644540 },
      { type = "boss", bossName = "Xathuux the Annihilator", support = 5, runsAnalyzed = 5, atMs = 1284465 },
      { type = "boss", bossName = "Lithiel Cinderfury", support = 5, runsAnalyzed = 5, atMs = 1897633 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 100, runsAnalyzed = 100, atMs = 20509 },
          { type = "boss", bossName = "Zaen Bladesorrow", support = 92, runsAnalyzed = 100, atMs = 628491 },
          { type = "boss", bossName = "Xathuux the Annihilator", support = 74, runsAnalyzed = 100, atMs = 1236350 },
          { type = "boss", bossName = "Lithiel Cinderfury", support = 56, runsAnalyzed = 100, atMs = 1826132 },
        },
      },
      p01 = {
        runsAnalyzed = 99,
        keystoneLevels = "20",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 99, runsAnalyzed = 99, atMs = 19952 },
          { type = "boss", bossName = "Zaen Bladesorrow", support = 96, runsAnalyzed = 99, atMs = 633083 },
          { type = "boss", bossName = "Xathuux the Annihilator", support = 93, runsAnalyzed = 99, atMs = 1249903 },
          { type = "boss", bossName = "Lithiel Cinderfury", support = 88, runsAnalyzed = 99, atMs = 1856950 },
        },
      },
    },
  },
  ["Ruby Life Pools"] = {
    runsAnalyzed = 5,
    keystoneLevels = "20/20/20/20/20",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 24762 },
      { type = "afterBoss", anchorBossName = "Melidrussa Chillworn", pullOffset = 1, support = 3, runsAnalyzed = 5, atMs = 646482 },
      { type = "afterBoss", anchorBossName = "Kokia Blazehoof", pullOffset = 1, support = 3, runsAnalyzed = 5, atMs = 1284695 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 99,
        keystoneLevels = "18",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 98, runsAnalyzed = 99, atMs = 24361 },
          { type = "afterBoss", anchorBossName = "Melidrussa Chillworn", pullOffset = 1, support = 78, runsAnalyzed = 99, atMs = 632161 },
          { type = "boss", bossName = "Kyrakka and Erkhart Stormvein", support = 55, runsAnalyzed = 99, atMs = 1404730 },
        },
      },
      p01 = {
        runsAnalyzed = 100,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 100, runsAnalyzed = 100, atMs = 24257 },
          { type = "afterBoss", anchorBossName = "Melidrussa Chillworn", pullOffset = 1, support = 72, runsAnalyzed = 100, atMs = 665667 },
          { type = "afterBoss", anchorBossName = "Kokia Blazehoof", pullOffset = 1, support = 68, runsAnalyzed = 100, atMs = 1289649 },
        },
      },
    },
  },
  ["Temple of Sethraliss"] = {
    runsAnalyzed = 5,
    keystoneLevels = "21/21/21/21/21",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 24789 },
      { type = "boss", bossName = "Galvazzt", support = 3, runsAnalyzed = 5, atMs = 1239139 },
      { type = "boss", bossName = "Avatar of Sethraliss", support = 5, runsAnalyzed = 5, atMs = 1842842 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 99, runsAnalyzed = 100, atMs = 22457 },
          { type = "boss", bossName = "Merektha", support = 67, runsAnalyzed = 100, atMs = 690589 },
          { type = "boss", bossName = "Avatar of Sethraliss", support = 81, runsAnalyzed = 100, atMs = 1603780 },
        },
      },
      p01 = {
        runsAnalyzed = 85,
        keystoneLevels = "20",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 84, runsAnalyzed = 85, atMs = 22230 },
          { type = "boss", bossName = "Avatar of Sethraliss", support = 66, runsAnalyzed = 85, atMs = 1705642 },
        },
      },
    },
  },
  ["The Blinding Vale"] = {
    runsAnalyzed = 5,
    keystoneLevels = "21/21/20/20/20",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 33680 },
      { type = "boss", bossName = "Ikuzz the Light Hunter", support = 5, runsAnalyzed = 5, atMs = 718727 },
      { type = "boss", bossName = "Ziekett", support = 5, runsAnalyzed = 5, atMs = 1488979 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 99,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 98, runsAnalyzed = 99, atMs = 29378 },
          { type = "boss", bossName = "Ikuzz the Light Hunter", support = 96, runsAnalyzed = 99, atMs = 735318 },
          { type = "boss", bossName = "Ziekett", support = 93, runsAnalyzed = 99, atMs = 1464063 },
        },
      },
      p01 = {
        runsAnalyzed = 73,
        keystoneLevels = "20",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 72, runsAnalyzed = 73, atMs = 30994 },
          { type = "boss", bossName = "Ikuzz the Light Hunter", support = 72, runsAnalyzed = 73, atMs = 750581 },
          { type = "boss", bossName = "Ziekett", support = 65, runsAnalyzed = 73, atMs = 1515898 },
        },
      },
    },
  },
  ["Voidscar Arena"] = {
    runsAnalyzed = 5,
    keystoneLevels = "21/20/20/20/20",
    generatedAt = "2026-09-10T11:23:35.039Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 25547 },
      { type = "boss", bossName = "Atroxus", support = 5, runsAnalyzed = 5, atMs = 769731 },
      { type = "boss", bossName = "Charonus", support = 4, runsAnalyzed = 5, atMs = 1427829 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "19",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 94, runsAnalyzed = 100, atMs = 25282 },
          { type = "boss", bossName = "Atroxus", support = 99, runsAnalyzed = 100, atMs = 783396 },
          { type = "boss", bossName = "Charonus", support = 97, runsAnalyzed = 100, atMs = 1441255 },
        },
      },
      p01 = {
        runsAnalyzed = 58,
        keystoneLevels = "20",
        generatedAt = "2026-09-10T11:23:35.039Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 54, runsAnalyzed = 58, atMs = 25547 },
          { type = "boss", bossName = "Atroxus", support = 57, runsAnalyzed = 58, atMs = 796758 },
          { type = "boss", bossName = "Charonus", support = 54, runsAnalyzed = 58, atMs = 1485104 },
        },
      },
    },
  },
}
