----------------------------------------------------------------------
-- ZugZug Keys — Lust Data
-- Curated per-dungeon overrides for the lust fallback (used when MDT
-- isn't loaded or the route has no recognisable lust marker). Indexed
-- by the challenge map ID from C_ChallengeMode.GetActiveChallengeMapID.
--
-- Each entry: { name, encounterIDs, note }
--   name: human label for chat output
--   encounterIDs: list of bossIDs (from ENCOUNTER_START) where lust is
--     recommended at the START of the encounter
--   note: free-form explanation shown in chat
--
-- DEFAULT BEHAVIOR: dungeons WITHOUT an entry here fall back to
-- "lust on the first boss of the run" — always sane, no IDs required.
-- Add an entry below only when the meta call for a dungeon is something
-- sharper (a specific later boss, or a boss the first-boss default gets
-- wrong). Grab the mapID + encounterID with /zzk lust debug output or
-- from ENCOUNTER_START in /eventtrace during a key.
--
-- Midnight S1 pool (see scripts/shared/encounters.ts):
--   Algeth'ar Academy · Magisters' Terrace · Maisara Caverns ·
--   Nexus-Point Xenas · Pit of Saron · Seat of Triumvirate ·
--   Skyreach · Windrunner Spire
--
-- FUTURE: these calls are derivable from WarcraftLogs — top M+ report
-- events contain the actual lust casts (Bloodlust 2825 / Heroism 32182 /
-- Time Warp 80353 / Fury of the Aspects 390386 / Primal Rage 264667)
-- with timestamps that map onto pulls. A weekly worker phase could write
-- the consensus call per dungeon and a generator script (like the main
-- addon's update-data.ts) could regenerate this file. Until then: curate
-- by hand or trust the first-boss default.
----------------------------------------------------------------------

ZugZugKeysLustData = {
  -- Example shape (uncomment + fill with real values):
  -- [503] = {
  --   name = "Algeth'ar Academy",
  --   encounterIDs = { 2562 },
  --   note = "Lust on Crawth — consensus from top S1 routes",
  -- },
}
