----------------------------------------------------------------------
-- ZugZug Keys — WCL-derived lust calls (AUTO-GENERATED)
-- Where the top M+ groups actually cast Bloodlust/Heroism/Time Warp,
-- derived weekly from WarcraftLogs top runs and regenerated by
-- scripts/update-lustdata.ts. Do not edit by hand — hand-curated
-- overrides belong in LustData.lua instead.
--
-- Generated: 2026-08-28T19:25:48.002Z
--
-- Call shapes (matched in-game by fuzzy boss-name comparison):
--   { type = "boss", bossName = X }             lust on that boss engage
--   { type = "afterBoss", pullOffset = N }      Nth pack from the run start
--   { type = "afterBoss", anchorBossName = X, pullOffset = N }
--                                               Nth pack after boss X dies
----------------------------------------------------------------------

ZugZugKeysWclLustData = {
  ["Altar of Fangs"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/18/18/18/18",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 21808 },
      { type = "afterBoss", anchorBossName = "Rav'i", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 685103 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 99, runsAnalyzed = 100, atMs = 24412 },
          { type = "afterBoss", anchorBossName = "Rav'i", pullOffset = 1, support = 94, runsAnalyzed = 100, atMs = 684413 },
        },
      },
      p01 = {
        runsAnalyzed = 76,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 75, runsAnalyzed = 76, atMs = 23809 },
          { type = "afterBoss", anchorBossName = "Rav'i", pullOffset = 1, support = 71, runsAnalyzed = 76, atMs = 713345 },
          { type = "afterBoss", anchorBossName = "The Writhing Coil", pullOffset = 3, support = 40, runsAnalyzed = 76, atMs = 1429871 },
        },
      },
    },
  },
  ["Den of Nalorakk"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/19/19/19/19",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 46956 },
      { type = "boss", bossName = "Nalorakk", support = 5, runsAnalyzed = 5, atMs = 1580546 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 98, runsAnalyzed = 100, atMs = 46547 },
          { type = "boss", bossName = "Nalorakk", support = 84, runsAnalyzed = 100, atMs = 1522154 },
        },
      },
      p01 = {
        runsAnalyzed = 100,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 93, runsAnalyzed = 100, atMs = 46283 },
          { type = "boss", bossName = "Nalorakk", support = 78, runsAnalyzed = 100, atMs = 1568549 },
        },
      },
    },
  },
  ["King's Rest"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/19/19/19/19",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 4, runsAnalyzed = 5, atMs = 50233 },
      { type = "boss", bossName = "King Dazar", support = 5, runsAnalyzed = 5, atMs = 1726978 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 67, runsAnalyzed = 100, atMs = 53694 },
          { type = "boss", bossName = "Mchimba the Embalmer", support = 64, runsAnalyzed = 100, atMs = 838213 },
          { type = "boss", bossName = "King Dazar", support = 84, runsAnalyzed = 100, atMs = 1612038 },
        },
      },
      p01 = {
        runsAnalyzed = 86,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 63, runsAnalyzed = 86, atMs = 52684 },
          { type = "boss", bossName = "King Dazar", support = 70, runsAnalyzed = 86, atMs = 1708900 },
        },
      },
    },
  },
  ["Murder Row"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/19/19/19/19",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 17241 },
      { type = "boss", bossName = "Zaen Bladesorrow", support = 5, runsAnalyzed = 5, atMs = 633591 },
      { type = "boss", bossName = "Xathuux the Annihilator", support = 4, runsAnalyzed = 5, atMs = 1288586 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 98, runsAnalyzed = 100, atMs = 22429 },
          { type = "boss", bossName = "Zaen Bladesorrow", support = 84, runsAnalyzed = 100, atMs = 631288 },
        },
      },
      p01 = {
        runsAnalyzed = 95,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 94, runsAnalyzed = 95, atMs = 22475 },
          { type = "boss", bossName = "Zaen Bladesorrow", support = 86, runsAnalyzed = 95, atMs = 633085 },
          { type = "boss", bossName = "Xathuux the Annihilator", support = 74, runsAnalyzed = 95, atMs = 1249624 },
          { type = "boss", bossName = "Lithiel Cinderfury", support = 66, runsAnalyzed = 95, atMs = 1846419 },
        },
      },
    },
  },
  ["Ruby Life Pools"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/19/19/19/19",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 23073 },
      { type = "afterBoss", anchorBossName = "Melidrussa Chillworn", pullOffset = 1, support = 3, runsAnalyzed = 5, atMs = 670214 },
      { type = "afterBoss", anchorBossName = "Kokia Blazehoof", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 1316682 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 100, runsAnalyzed = 100, atMs = 24635 },
          { type = "afterBoss", anchorBossName = "Melidrussa Chillworn", pullOffset = 1, support = 79, runsAnalyzed = 100, atMs = 664827 },
          { type = "boss", bossName = "Kyrakka and Erkhart Stormvein", support = 64, runsAnalyzed = 100, atMs = 1440873 },
        },
      },
      p01 = {
        runsAnalyzed = 76,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 75, runsAnalyzed = 76, atMs = 24142 },
          { type = "afterBoss", anchorBossName = "Melidrussa Chillworn", pullOffset = 1, support = 61, runsAnalyzed = 76, atMs = 675805 },
        },
      },
    },
  },
  ["Temple of Sethraliss"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/19/19/19/19",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 23497 },
      { type = "afterBoss", anchorBossName = "Adderis and Aspix", pullOffset = 1, support = 3, runsAnalyzed = 5, atMs = 623573 },
      { type = "boss", bossName = "Galvazzt", support = 4, runsAnalyzed = 5, atMs = 1270546 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 100, runsAnalyzed = 100, atMs = 25357 },
          { type = "boss", bossName = "Merektha", support = 81, runsAnalyzed = 100, atMs = 697494 },
          { type = "boss", bossName = "Avatar of Sethraliss", support = 85, runsAnalyzed = 100, atMs = 1562661 },
        },
      },
      p01 = {
        runsAnalyzed = 99,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 98, runsAnalyzed = 99, atMs = 25182 },
          { type = "boss", bossName = "Merektha", support = 62, runsAnalyzed = 99, atMs = 740064 },
          { type = "boss", bossName = "Avatar of Sethraliss", support = 69, runsAnalyzed = 99, atMs = 1690494 },
        },
      },
    },
  },
  ["The Blinding Vale"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/19/18/18/18",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 28554 },
      { type = "boss", bossName = "Ikuzz the Light Hunter", support = 5, runsAnalyzed = 5, atMs = 715728 },
      { type = "boss", bossName = "Ziekett", support = 4, runsAnalyzed = 5, atMs = 1355279 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 99, runsAnalyzed = 100, atMs = 27088 },
          { type = "boss", bossName = "Ikuzz the Light Hunter", support = 95, runsAnalyzed = 100, atMs = 711611 },
          { type = "boss", bossName = "Ziekett", support = 82, runsAnalyzed = 100, atMs = 1446883 },
        },
      },
      p01 = {
        runsAnalyzed = 73,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 73, runsAnalyzed = 73, atMs = 27285 },
          { type = "boss", bossName = "Ikuzz the Light Hunter", support = 73, runsAnalyzed = 73, atMs = 750262 },
          { type = "boss", bossName = "Ziekett", support = 68, runsAnalyzed = 73, atMs = 1488041 },
        },
      },
    },
  },
  ["Voidscar Arena"] = {
    runsAnalyzed = 5,
    keystoneLevels = "19/18/18/18/18",
    generatedAt = "2026-08-28T19:25:48.002Z",
    calls = {
      { type = "afterBoss", pullOffset = 1, support = 5, runsAnalyzed = 5, atMs = 22903 },
      { type = "boss", bossName = "Atroxus", support = 5, runsAnalyzed = 5, atMs = 803658 },
      { type = "boss", bossName = "Charonus", support = 5, runsAnalyzed = 5, atMs = 1419143 },
    },
    cohorts = {
      p1 = {
        runsAnalyzed = 100,
        keystoneLevels = "17",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 98, runsAnalyzed = 100, atMs = 24848 },
          { type = "boss", bossName = "Atroxus", support = 90, runsAnalyzed = 100, atMs = 809053 },
          { type = "boss", bossName = "Charonus", support = 98, runsAnalyzed = 100, atMs = 1442816 },
        },
      },
      p01 = {
        runsAnalyzed = 61,
        keystoneLevels = "18",
        generatedAt = "2026-08-28T19:25:48.002Z",
        calls = {
          { type = "afterBoss", pullOffset = 1, support = 59, runsAnalyzed = 61, atMs = 24952 },
          { type = "boss", bossName = "Atroxus", support = 56, runsAnalyzed = 61, atMs = 804540 },
          { type = "boss", bossName = "Charonus", support = 56, runsAnalyzed = 61, atMs = 1476229 },
        },
      },
    },
  },
}
