/**
 * Fetch WCL-derived lust calls and regenerate LustDataWCL.lua.
 *
 * Usage:  npx tsx scripts/update-lustdata.ts
 *
 * Default source is the cron worker's public endpoint (the worker derives
 * the calls weekly from top WCL M+ logs). For local experimentation you can
 * bypass the worker and hit WCL directly by setting WCL_V2_CLIENT_ID and
 * WCL_V2_CLIENT_SECRET in the environment — the script then imports the
 * shared derivation module from the sibling zugzug.info repo.
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const API_URL = "https://zugzug-cron.zugzugio.workers.dev/api/lust-calls";

// ─── Types (mirror zugzug.info shared/src/wclLust.ts — kept minimal) ────────

interface LustCall {
  type: "boss" | "afterBoss";
  bossName?: string;
  anchorBossName?: string | null;
  pullOffset?: number;
  support: number;
  runsAnalyzed: number;
  medianAt: number;
  /** Median cast time in ms from run start (0/absent = unknown). */
  medianAtMs?: number;
}

interface DungeonLustCalls {
  dungeonName: string;
  runsAnalyzed: number;
  keystoneLevels: number[];
  calls: LustCall[];
  /** Alternate leaderboard cohorts (p1 ≈ top-1%, p01 ≈ low end of top-0.1%);
   *  the entry itself is the "top" cohort. */
  cohorts?: Partial<Record<"p1" | "p01", Omit<DungeonLustCalls, "cohorts">>>;
}

interface LustCallsBlob {
  generatedAt: string;
  dungeons: DungeonLustCalls[];
}

// ─── Lua serialization (same conventions as the main addon's generator) ─────

function luaStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

function callToLua(c: LustCall, indent: string): string {
  const fields: string[] = [`type = ${luaStr(c.type)}`];
  if (c.type === "boss") {
    fields.push(`bossName = ${luaStr(c.bossName ?? "")}`);
  } else {
    if (c.anchorBossName) fields.push(`anchorBossName = ${luaStr(c.anchorBossName)}`);
    fields.push(`pullOffset = ${c.pullOffset ?? 1}`);
  }
  fields.push(`support = ${c.support}`, `runsAnalyzed = ${c.runsAnalyzed}`);
  // Median cast time (ms from key start) → timer-bar tick in the addon.
  if (typeof c.medianAtMs === "number" && c.medianAtMs > 0) {
    fields.push(`atMs = ${Math.round(c.medianAtMs)}`);
  }
  return `${indent}{ ${fields.join(", ")} },`;
}

/** "24/24/23" for small samples, "23-25" for big ones (100-run cohorts
 *  would otherwise write a 100-item string into the Lua). */
function keyLevelSummary(levels: number[]): string {
  if (levels.length === 0) return "?";
  if (levels.length <= 6) return levels.join("/");
  const min = Math.min(...levels);
  const max = Math.max(...levels);
  return min === max ? String(min) : `${min}-${max}`;
}

/** One cohort body (runsAnalyzed/keystoneLevels/calls) at the given indent. */
function cohortBodyToLua(
  d: Omit<DungeonLustCalls, "cohorts">,
  generatedAt: string,
  indent: string,
): string[] {
  const lines: string[] = [];
  lines.push(`${indent}runsAnalyzed = ${d.runsAnalyzed},`);
  lines.push(`${indent}keystoneLevels = ${luaStr(keyLevelSummary(d.keystoneLevels))},`);
  lines.push(`${indent}generatedAt = ${luaStr(generatedAt)},`);
  lines.push(`${indent}calls = {`);
  for (const c of d.calls) lines.push(callToLua(c, indent + "  "));
  lines.push(`${indent}},`);
  return lines;
}

function blobToLua(blob: LustCallsBlob): string {
  const lines: string[] = [];
  lines.push("----------------------------------------------------------------------");
  lines.push("-- ZugZug Keys — WCL-derived lust calls (AUTO-GENERATED)");
  lines.push("-- Where the top M+ groups actually cast Bloodlust/Heroism/Time Warp,");
  lines.push("-- derived weekly from WarcraftLogs top runs and regenerated by");
  lines.push("-- scripts/update-lustdata.ts. Do not edit by hand — hand-curated");
  lines.push("-- overrides belong in LustData.lua instead.");
  lines.push("--");
  lines.push(`-- Generated: ${blob.generatedAt}`);
  lines.push("--");
  lines.push("-- Call shapes (matched in-game by fuzzy boss-name comparison):");
  lines.push('--   { type = "boss", bossName = X }             lust on that boss engage');
  lines.push('--   { type = "afterBoss", pullOffset = N }      Nth pack from the run start');
  lines.push('--   { type = "afterBoss", anchorBossName = X, pullOffset = N }');
  lines.push("--                                               Nth pack after boss X dies");
  lines.push("----------------------------------------------------------------------");
  lines.push("");
  lines.push("ZugZugKeysWclLustData = {");
  for (const d of blob.dungeons) {
    const hasCohortCalls =
      d.cohorts && Object.values(d.cohorts).some((c) => c && c.calls.length > 0);
    if (d.calls.length === 0 && !hasCohortCalls) continue;
    lines.push(`  [${luaStr(d.dungeonName)}] = {`);
    // Top-level body = the "top" (rank 1-N) cohort — also the fallback the
    // addon uses when a selected cohort is missing/empty.
    lines.push(...cohortBodyToLua(d, blob.generatedAt, "    "));
    if (hasCohortCalls) {
      lines.push(`    cohorts = {`);
      for (const key of ["p1", "p01"] as const) {
        const c = d.cohorts?.[key];
        if (!c || c.calls.length === 0) continue;
        lines.push(`      ${key} = {`);
        lines.push(...cohortBodyToLua(c, blob.generatedAt, "        "));
        lines.push(`      },`);
      }
      lines.push(`    },`);
    }
    lines.push(`  },`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function fetchBlob(): Promise<LustCallsBlob> {
  // Highest priority: a pre-derived blob file (e.g. from a local sweep run
  // when WCL's per-IP throttle blocks deriving from shared egress IPs).
  const blobFile = process.env.LUST_BLOB_FILE;
  if (blobFile) {
    console.log(`Reading blob from ${blobFile} ...`);
    const { readFileSync } = await import("node:fs");
    return JSON.parse(readFileSync(blobFile, "utf-8")) as LustCallsBlob;
  }

  const clientId = process.env.WCL_V2_CLIENT_ID;
  const clientSecret = process.env.WCL_V2_CLIENT_SECRET;
  if (clientId && clientSecret) {
    console.log("WCL creds in env — deriving directly from WarcraftLogs...");
    const sharedPath = resolve(
      dirname(fileURLToPath(import.meta.url)),
      "../../zugzug.info/shared/src/wclLust.ts",
    );
    const shared = await import(pathToFileURL(sharedPath).href);
    const store = new Map<string, string>();
    const fakeKV = {
      get: async (k: string) => store.get(k) ?? null,
      put: async (k: string, v: string) => void store.set(k, v),
    };
    return (await shared.refreshLustCalls({ clientId, clientSecret }, fakeKV)) as LustCallsBlob;
  }

  console.log(`Fetching ${API_URL} ...`);
  const res = await fetch(API_URL, { headers: { Accept: "application/json" } });
  if (!res.ok) {
    throw new Error(`API returned ${res.status}: ${await res.text()}`);
  }
  return (await res.json()) as LustCallsBlob;
}

async function main() {
  const blob = await fetchBlob();
  const withCalls = blob.dungeons.filter((d) => d.calls.length > 0);
  console.log(`Got calls for ${withCalls.length}/${blob.dungeons.length} dungeons (generated ${blob.generatedAt})`);
  for (const d of withCalls) {
    console.log(`  ${d.dungeonName}: ${d.calls.length} calls from ${d.runsAnalyzed} runs`);
  }

  if (withCalls.length === 0) {
    throw new Error("Blob contains zero calls — refusing to write an empty LustDataWCL.lua");
  }

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(__dirname, "..", "LustDataWCL.lua");
  writeFileSync(outPath, blobToLua(blob), "utf-8");
  console.log(`\nWrote ${outPath}`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
